# Generated by Django 4.0 on 2021-12-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grocery',
        ),
    ]
